name: run web test
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: pull project on runner
        uses: actions/checkout@v3
      - name: java set up
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
          
      - name: Run tests
        env:
          SELENIUM_HUB_HOST: 'localhost'
        run: mvn clean test -Dcucumber.filter.tags="@smoke"
        
      - name: Upload report
        uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: html-report
          path: ./target/cucumber/cucumber.html
      
      - name: Download HTML report artifact
        uses: actions/download-artifact@v2
        if: ${{ success() }}
        with:
          name: html-report
          
      - name: Deploy report to Github Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/cucumber/

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
