name: run web test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: pull project on runner
        uses: actions/checkout@v3

      - name: java set up
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - uses: actions/checkout@v1
      
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Run tests
        env:
          SELENIUM_HUB_HOST: 'localhost'
        run: mvn clean test -Dcucumber.filter.tags="@smoke"
        
      - name: Upload artifact report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Test Reports
          path: ./target/cucumber.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/cucumber.html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
