name: run web test

on: workflow_dispatch
jobs:
  run-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: pull project on runner
        uses: actions/checkout@v3

      - name: java set up
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - uses: actions/checkout@v1
      
      - name: Run tests
        run: mvn clean test -Dcucumber.filter.tags="@smoke"
    
